import re
import unicodedata


TAGS_VAGAS_TI_DADOS = [
    "Data",
    "Dados",
    "Data Engineer",
    "Engenheiro de Dados",
    "Engenharia de Dados",
    "Data Engineering",
    "Senior Data Engineer",
    "Junior Data Engineer",
    "Mid-Level Data Engineer",
    "Lead Data Engineer",
    "Staff Data Engineer",
    "Principal Data Engineer",
    "Cloud Data Engineer",
    "Big Data Engineer",
    "Data Platform Engineer",
    "Data Infrastructure Engineer",
    "Analytics Engineer",
    "Engenheiro Analytics",
    "Data Analyst",
    "Analista de Dados",
    "BI Analyst",
    "Business Intelligence Analyst",
    "BI Developer",
    "Data Developer",
    "ETL Developer",
    "ELT Developer",
    "Data Architect",
    "Arquiteto de Dados",
    "Database Engineer",
    "DBA",
    "Backend Engineer",
    "Software Engineer",
    "Software Engineer Data",
    "Python Developer",
    "RPA Developer",
    "Automation Developer",
    "Integration Engineer",
    "Solutions Engineer",
    "Platform Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "AI Engineer",
    "Machine Learning Engineer",
    "ML Engineer",
    "MLOps Engineer",
    "AI Data Engineer",
    "Data & AI Engineer",
    "GenAI Engineer",
    "LLM Engineer",
    "Prompt Engineer",
    "Agentic AI Engineer",
    "Python",
    "SQL",
    "Advanced SQL",
    "SQL Avancado",
    "SQL Avancado",
    "PySpark",
    "Spark SQL",
    "Scala",
    "Java",
    "Bash",
    "Shell Script",
    "PowerShell",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "C#",
    ".NET",
    "R",
    "Go",
    "Rust",
    "Pandas",
    "Polars",
    "NumPy",
    "PyArrow",
    "SQLAlchemy",
    "Requests",
    "BeautifulSoup",
    "Scrapy",
    "Selenium",
    "Playwright",
    "FastAPI",
    "Flask",
    "Django",
    "Pydantic",
    "Jupyter",
    "Notebook",
    "Regex",
    "JSON",
    "XML",
    "YAML",
    "CSV",
    "Parquet",
    "Avro",
    "ORC",
    "Delta",
    "Delta Table",
    "ETL",
    "ELT",
    "Data Pipeline",
    "Pipeline de Dados",
    "Data Pipelines",
    "Batch Processing",
    "Stream Processing",
    "Streaming Data",
    "Real Time Data",
    "Near Real Time",
    "Data Ingestion",
    "Data Integration",
    "Data Transformation",
    "Data Modeling",
    "Modelagem de Dados",
    "Dimensional Modeling",
    "Modelagem Dimensional",
    "Star Schema",
    "Snowflake Schema",
    "Fact Table",
    "Dimension Table",
    "SCD",
    "Slowly Changing Dimension",
    "CDC",
    "Change Data Capture",
    "Incremental Load",
    "Full Load",
    "Data Warehouse",
    "Data Warehousing",
    "Data Lake",
    "Data Lakehouse",
    "Lakehouse",
    "Data Mart",
    "Data Mesh",
    "Data Fabric",
    "Data Platform",
    "Data Infrastructure",
    "Data Architecture",
    "Data Governance",
    "Governanca de Dados",
    "Data Quality",
    "Qualidade de Dados",
    "Data Observability",
    "Data Lineage",
    "Data Catalog",
    "Metadata",
    "Master Data Management",
    "MDM",
    "OLAP",
    "OLTP",
    "Cloud",
    "Cloud Computing",
    "AWS",
    "Amazon Web Services",
    "GCP",
    "Google Cloud",
    "Google Cloud Platform",
    "Azure",
    "Microsoft Azure",
    "Multi Cloud",
    "Serverless",
    "Infrastructure as Code",
    "IaC",
    "AWS S3",
    "Amazon S3",
    "AWS Glue",
    "AWS Athena",
    "Amazon Athena",
    "AWS Lambda",
    "AWS Redshift",
    "Amazon Redshift",
    "Redshift Spectrum",
    "AWS EMR",
    "Amazon EMR",
    "AWS Step Functions",
    "AWS Batch",
    "AWS DMS",
    "AWS RDS",
    "AWS Aurora",
    "AWS DynamoDB",
    "DynamoDB",
    "AWS Kinesis",
    "Amazon Kinesis",
    "AWS MSK",
    "AWS ECS",
    "AWS EKS",
    "AWS EC2",
    "AWS CloudWatch",
    "AWS CloudTrail",
    "AWS IAM",
    "AWS Secrets Manager",
    "AWS Lake Formation",
    "AWS EventBridge",
    "AWS SNS",
    "AWS SQS",
    "AWS Bedrock",
    "AWS SageMaker",
    "BigQuery",
    "Google BigQuery",
    "Cloud Storage",
    "GCS",
    "Dataflow",
    "Dataproc",
    "Cloud Composer",
    "Pub/Sub",
    "Google Pub/Sub",
    "Cloud Functions",
    "Cloud Run",
    "Vertex AI",
    "Looker",
    "Looker Studio",
    "Dataform",
    "Cloud SQL",
    "Spanner",
    "Firestore",
    "Bigtable",
    "Google Secret Manager",
    "Google IAM",
    "Cloud Logging",
    "Cloud Monitoring",
    "Azure Data Factory",
    "ADF",
    "Azure Synapse",
    "Azure Databricks",
    "Azure Data Lake",
    "Azure Data Lake Storage",
    "ADLS",
    "Azure Blob Storage",
    "Azure SQL",
    "Azure Functions",
    "Azure Event Hubs",
    "Azure Stream Analytics",
    "Azure Cosmos DB",
    "Azure DevOps",
    "Microsoft Fabric",
    "OneLake",
    "Power BI",
    "Azure Machine Learning",
    "Azure Key Vault",
    "Logic Apps",
    "Apache Spark",
    "Spark",
    "Databricks",
    "Delta Lake",
    "Apache Flink",
    "Flink",
    "Apache Beam",
    "Hadoop",
    "Hive",
    "Presto",
    "Trino",
    "Impala",
    "HBase",
    "MapReduce",
    "Apache Iceberg",
    "Iceberg",
    "Apache Hudi",
    "Hudi",
    "Kafka",
    "Apache Kafka",
    "Kafka Streams",
    "Kafka Connect",
    "Confluent",
    "RabbitMQ",
    "Event Streaming",
    "Message Queue",
    "Message Broker",
    "Airflow",
    "Apache Airflow",
    "Astronomer",
    "MWAA",
    "Dagster",
    "Prefect",
    "Luigi",
    "Oozie",
    "dbt Cloud",
    "dbt Core",
    "Cron",
    "Crontab",
    "Step Functions",
    "Argo Workflows",
    "dbt",
    "Analytics Engineering",
    "SQL Modeling",
    "dbt Models",
    "dbt Tests",
    "dbt Seeds",
    "dbt Snapshots",
    "dbt Macros",
    "Jinja",
    "Data Contracts",
    "Semantic Layer",
    "Metrics Layer",
    "Data Documentation",
    "Data Testing",
    "Great Expectations",
    "Soda",
    "Elementary",
    "Monte Carlo",
    "Datafold",
    "PostgreSQL",
    "Postgres",
    "MySQL",
    "SQL Server",
    "Oracle",
    "MariaDB",
    "SQLite",
    "MongoDB",
    "Cassandra",
    "Redis",
    "Elasticsearch",
    "OpenSearch",
    "Snowflake",
    "Redshift",
    "Databricks SQL",
    "Synapse",
    "Teradata",
    "Vertica",
    "ClickHouse",
    "DuckDB",
    "Athena",
    "Firebolt",
    "Greenplum",
    "Tableau",
    "Metabase",
    "Qlik",
    "Qlik Sense",
    "MicroStrategy",
    "Apache Superset",
    "Superset",
    "Grafana",
    "Kibana",
    "Excel",
    "Google Sheets",
    "Dashboard",
    "Dashboards",
    "Reporting",
    "Reports",
    "Business Intelligence",
    "BI",
    "Data Visualization",
    "Visualizacao de Dados",
    "Data Storytelling",
    "KPI",
    "Metrics",
    "Indicadores",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Jenkins",
    "Docker",
    "Docker Compose",
    "Kubernetes",
    "K8s",
    "Terraform",
    "CloudFormation",
    "Helm",
    "Linux",
    "Ubuntu",
    "Nginx",
    "API",
    "REST API",
    "GraphQL",
    "Webhook",
    "Webhooks",
    "OAuth",
    "OAuth2",
    "JWT",
    "Postman",
    "Insomnia",
    "Monitoring",
    "Logging",
    "Observability",
    "Prometheus",
    "New Relic",
    "Datadog",
    "Sentry",
    "Airbyte",
    "Fivetran",
    "Stitch",
    "Meltano",
    "Singer",
    "Hevo",
    "Matillion",
    "Talend",
    "Informatica",
    "SSIS",
    "Pentaho",
    "n8n",
    "Zapier",
    "Make",
    "Workato",
    "RPA",
    "Robotic Process Automation",
    "UiPath",
    "Automation Anywhere",
    "Power Automate",
    "Web Scraping",
    "Crawling",
    "Bots",
    "Automation",
    "Automacao",
    "AI",
    "Artificial Intelligence",
    "Inteligencia Artificial",
    "Generative AI",
    "GenAI",
    "IA Generativa",
    "LLM",
    "Large Language Models",
    "Large Language Model",
    "ChatGPT",
    "OpenAI",
    "Claude",
    "Anthropic",
    "Gemini",
    "Google Gemini",
    "DeepSeek",
    "Llama",
    "Llama 3",
    "Llama 4",
    "Mistral",
    "Mixtral",
    "Cohere",
    "Perplexity",
    "Grok",
    "Copilot",
    "GitHub Copilot",
    "Cursor",
    "Windsurf",
    "Vibe Coding",
    "Vibbe Coding",
    "AI Coding",
    "Prompt Engineering",
    "Engenharia de Prompt",
    "Prompt Design",
    "Prompt Optimization",
    "Prompt Chaining",
    "Few-Shot Prompting",
    "Zero-Shot Prompting",
    "Chain of Thought",
    "Reasoning Models",
    "Tool Calling",
    "Function Calling",
    "Structured Outputs",
    "JSON Mode",
    "LLM Evaluation",
    "LLM Observability",
    "LLMOps",
    "Model Evaluation",
    "Guardrails",
    "AI Guardrails",
    "Safety Evaluation",
    "Hallucination Detection",
    "Synthetic Data",
    "Fine Tuning",
    "Fine-Tuning",
    "Instruction Tuning",
    "RAG",
    "Retrieval Augmented Generation",
    "Agentic RAG",
    "Graph RAG",
    "Hybrid Search",
    "Semantic Search",
    "Vector Search",
    "Vector Database",
    "Vector DB",
    "Embeddings",
    "Text Embeddings",
    "Embedding Models",
    "Chunking",
    "Reranking",
    "Reranker",
    "Information Retrieval",
    "Knowledge Base",
    "Knowledge Graph",
    "Pinecone",
    "Weaviate",
    "ChromaDB",
    "Chroma",
    "FAISS",
    "Milvus",
    "Qdrant",
    "pgvector",
    "Elasticsearch Vector Search",
    "OpenSearch Vector Search",
    "AI Agents",
    "Agentic AI",
    "Agentic",
    "Agentic Workflows",
    "Agentic Systems",
    "Autonomous Agents",
    "Autonomous AI Agents",
    "Multi-Agent Systems",
    "Multi Agent",
    "Multi-Agent",
    "AI Agent Orchestration",
    "Agent Orchestration",
    "Workflow Orchestration",
    "Agent Frameworks",
    "Agent Framework",
    "Agent Builder",
    "Agent Runtime",
    "Agent Tools",
    "Tool Use",
    "Tool-Using Agents",
    "Planning Agents",
    "Reasoning Agents",
    "ReAct",
    "Reflection",
    "Self-Reflection",
    "Memory",
    "Agent Memory",
    "Long-Term Memory",
    "Short-Term Memory",
    "Task Decomposition",
    "Human in the Loop",
    "HITL",
    "Multi-Step Reasoning",
    "Autonomous Workflow",
    "AI Workflow Automation",
    "Conversational Agents",
    "Chatbots",
    "Voice Agents",
    "AI Assistants",
    "Virtual Assistant",
    "LangChain",
    "LangGraph",
    "LangSmith",
    "LlamaIndex",
    "CrewAI",
    "AutoGen",
    "Microsoft AutoGen",
    "AG2",
    "Semantic Kernel",
    "Pydantic AI",
    "OpenAI Agents SDK",
    "OpenAI Assistants API",
    "Claude MCP",
    "MCP",
    "Model Context Protocol",
    "A2A",
    "Agent-to-Agent",
    "Haystack",
    "DSPy",
    "Flowise",
    "Dify",
    "Botpress",
    "Rasa",
    "Griptape",
    "AutoGPT",
    "BabyAGI",
    "Machine Learning",
    "ML",
    "MLOps",
    "Feature Store",
    "Feature Engineering",
    "Model Deployment",
    "Model Serving",
    "Model Monitoring",
    "Model Registry",
    "MLflow",
    "Kubeflow",
    "SageMaker",
    "Azure ML",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "XGBoost",
    "LightGBM",
    "Time Series",
    "Series Temporais",
    "Forecasting",
    "NLP",
    "Natural Language Processing",
    "Computer Vision",
    "Recommendation Systems",
    "LGPD",
    "GDPR",
    "Data Privacy",
    "Data Security",
    "IAM",
    "Access Control",
    "RBAC",
    "Secrets Management",
    "Encryption",
    "PII",
    "Sensitive Data",
    "Data Masking",
    "Data Anonymization",
    "Audit Logs",
    "Compliance",
    "SOC2",
    "ISO 27001",
    "Product Analytics",
    "Marketing Analytics",
    "Growth Analytics",
    "Financial Analytics",
    "Customer Analytics",
    "CRM Analytics",
    "Revenue Analytics",
    "Sales Analytics",
    "Web Analytics",
    "Digital Analytics",
    "Google Analytics",
    "GA4",
    "Google Tag Manager",
    "GTM",
    "Mixpanel",
    "Amplitude",
    "Segment",
    "HubSpot",
    "Salesforce",
    "Dynamics",
    "Microsoft Dynamics",
    "ERP",
    "CRM",
    "Marketplace",
    "E-commerce",
    "Fintech",
    "Insurtech",
    "SaaS",
    "Agile",
    "Scrum",
    "Kanban",
    "Jira",
    "ClickUp",
    "Confluence",
    "Documentation",
    "Technical Documentation",
    "Documentacao Tecnica",
    "Stakeholder Management",
    "Data-Driven",
    "Problem Solving",
    "Ownership",
    "Communication",
    "Cross-Functional",
    "Requirements Gathering",
    "Business Rules",
    "System Design",
    "Data Product",
    "Data as a Product",
]


def _normalize_text(value):
    normalized = unicodedata.normalize("NFKD", str(value or ""))
    normalized = "".join(char for char in normalized if not unicodedata.combining(char))
    return normalized.lower()


def _pattern_for_tag(tag):
    escaped = re.escape(_normalize_text(tag).strip())
    escaped = escaped.replace(r"\ ", r"[\s/_-]+")
    escaped = escaped.replace(r"\-", r"[-\s_/]*")
    escaped = escaped.replace(r"\.", r"[\.\s]*")
    escaped = escaped.replace(r"\/", r"[/\s-]*")
    escaped = escaped.replace(r"\&", r"(?:&|and|e)")
    return re.compile(rf"(?<![a-z0-9]){escaped}(?![a-z0-9])", re.IGNORECASE)


TAG_PATTERNS = [(tag, _pattern_for_tag(tag)) for tag in TAGS_VAGAS_TI_DADOS]


def build_job_tags(doc):
    chunks = [
        doc.get("title", ""),
        doc.get("company", ""),
        doc.get("location", ""),
        doc.get("keyword", ""),
        doc.get("job_type", ""),
        doc.get("discipline", ""),
        doc.get("job_function", ""),
        doc.get("seniority_level", ""),
        doc.get("industries", ""),
        doc.get("salary", ""),
        doc.get("posted_text", ""),
        doc.get("description", ""),
    ]
    haystack = _normalize_text("\n".join(str(chunk or "") for chunk in chunks))
    matches = []
    for tag, pattern in TAG_PATTERNS:
        if pattern.search(haystack):
            matches.append(tag)
    return matches
